name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    environment: 
      name: Development

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dpendencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Run lint
      run: cd starter/backend && pipenv run lint

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup python
      uses:  actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      working-directory: starter/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Run test
      run: cd starter/backend && pipenv install pytest && pipenv run test

      
  Build:
    needs: [Linting, Test]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        cd starter/backend
        docker build --tag mp-backend:latest .


