name: Frontend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    environment: Devlopmnet Environment

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Install dependencies
      working-directory: starter/frontend
      run: npm ci

    - name: Run Lint
      run: cd starter/frontend && npm run lint

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: starter/frontend
      run: npm ci
  
    - name: Run test
      run: cd starter/frontend && npm run test



  Build:
    needs: [Linting, Test]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
  

    - name: Login to Amazon 
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2



    - name: Build and push Docker Image
      working-directory: starter/frontend
      env:
        IMAGE_TAG: latest
        REPO_NAME: frontend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag 233718526883.dkr.ecr.us-east-1.amazonaws.com/$REPO_FRONTEND:$IMAGE_TAG .
        docker push 233718526883.dkr.ecr.us-east-1.amazonaws.com/$REPO_FRONTEND:$IMAGE_TAG
    

    - name: Configure Kubeconfig
      run:
       aws eks update-kubeconfig --name udacity-project4 --region us-east-1


    - name: Deploy Docker Image to Amazon EKS
      working-directory: starter/frontend/k8s
      env:
        IMAGE_TAG: latest
        REPO_NAME: frontend
      run: |
          kustomize edit set image frontend=233718526883.dkr.ecr.us-east-1.amazonaws.com/$REPO_FRONTEND:$IMAGE_TAG
          kustomize build | kubectl apply -f -
